# /etc/keyd/default.conf

[ids]
*

[global]
default_layout = xwin

[xwin:layout]
backspace = overload(meta, backspace)
delete = command(keyd do f12 && /home/jfin/.bin/get-keyd-status)
f12 = setlayout(tmux)

[tmux:layout]
backspace = overload(alt, backspace)
delete = command(keyd do f12 && /home/jfin/.bin/get-keyd-status)
f12 = setlayout(xwin)

[control]
backspace = backspace
delete = delete
