[ids]
*

[global]
default_layout = xwin

[xwin:layout]
backspace = overload(meta, backspace)
delete = setlayout(tmux)

[tmux:layout]
backspace = overload(alt, backspace)
delete = setlayout(xwin)

[control]
backspace = backspace
delete = delete
