#######################################################################
#                               options                               #
#######################################################################

# Color names:
# [bright]black   [bright]red       [bright]green   [bright]yellow
# [bright]blue    [bright]magenta   [bright]cyan    [bright]white
set -g base-index 1
set -g default-command /usr/bin/fish
set -g message-style fg=white,bg=default
set -g prefix None
set -g status off
set -g status-left ''
set -g status-right '%a %b %d %H:%M'
set -g status-style fg=white,bg=default

# may need -w flag
set -g mode-keys vi
set -g mode-style bg=brightblack
set -g pane-active-border-style fg=brightblack
set -g pane-border-lines heavy
set -g pane-border-style fg=brightblack

setw -g main-pane-width 80

#######################################################################
#                            key bindings                             #
#######################################################################

bind-key -n M-Enter split-window -b\;\
    select-layout main-vertical
bind-key -n M-\\ split-window -b -c '#{pane_current_path}'\;\
    select-layout main-vertical
bind-key -n M-BSpace kill-pane\;\
    select-layout main-vertical

bind-key -n M-j select-pane -Z -t .+ 
bind-key -n M-k select-pane -Z -t .-
bind-key -n M-u swap-pane -t '{top-left}'\;\
    select-pane -t '{top-left}'\;\
    select-layout main-vertical
bind-key -n M-o swap-pane -t '{top-left}'\;\
    select-pane -t '{top-left}'\;\
    select-layout main-horizontal
bind-key -n M-space resize-pane -Z

bind-key -n M-h select-window -t :-
bind-key -n M-l select-window -t :+ 
bind-key -n M-H join-pane -bt:-.'{top-left}'\;\
    select-layout main-vertical
bind-key -n M-L if-shell\
    '(( #{==:#{session_windows},#{window_index}} ))'\
    'break-pane -t:+'\
    'join-pane -bt:+."{top-left}"; select-layout main-vertical'
bind-key -n M-1 if-shell\
    'tmux select-window -t :1'\
    ''\
    'new-window -t :1'
bind-key -n M-2 if-shell\
    'tmux select-window -t :2'\
    ''\
    'new-window -t :2'
bind-key -n M-3 if-shell\
    'tmux select-window -t :3'\
    ''\
    'new-window -t :3'
bind-key -n M-4 if-shell\
    'tmux select-window -t :4'\
    ''\
    'new-window -t :4'
bind-key -n M-! if-shell\
    'tmux join-pane -bt :1.{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :1'
bind-key -n M-@ if-shell\
    'tmux join-pane -t :2.{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :2'
bind-key -n M-# if-shell\
    'tmux join-pane -t :3.{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :3'
bind-key -n M-$ if-shell\
    'tmux join-pane -t :4.{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :4'

bind-key -n M-: command-prompt
bind-key -n M-, run-shell -C 'set -g status'\;\
    run-shell -C -d 2 'set -g status'

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'cat > /dev/clipboard'
bind-key -n M-[ copy-mode
bind-key -n M-p paste-buffer
