# general options
set-option -g status on
set-option -g prefix None
set-option -g base-index 1
set-option -g default-command /usr/bin/ksh
set-option -g default-terminal tmux-256color
set-option -g status-right ""
set-window-option -g mode-keys vi
set-window-option -g pane-border-lines simple

# color options
# vocabulary:
#     [bright]black   [bright]red       [bright]green   [bright]yellow
#     [bright]blue    [bright]magenta   [bright]cyan    [bright]white
set-option -g status-style fg=brightblack,bg=default
set-option -g message-style fg=brightblack,bg=default
set-window-option -g mode-style bg=brightyellow
set-window-option -g pane-active-border-style fg=brightwhite,bg=default
set-window-option -g pane-border-style fg=brightwhite,bg=default

# general bindings
bind-key -n M-Enter split-window -b\;\
    select-layout main-vertical
bind-key -n M-: command-prompt
bind-key -n M-J select-window -t :+ 
bind-key -n M-K select-window -t :-
bind-key -n M-j select-pane -Z -t .+ 
bind-key -n M-Tab select-pane -Z -t .+ 
bind-key -n M-k select-pane -Z -t .-
bind-key -n M-BSpace kill-pane\;\
    select-layout main-vertical
bind-key -n M-space resize-pane -Z
bind-key -n M-i swap-pane -t {top-left}\;\
    select-pane -t {top-left}\;\
    select-layout main-vertical
bind-key -n M-o swap-pane -t {top-left}\;\
    select-pane -t {top-left}\;\
    select-layout main-horizontal

# window bindings
# window 1
bind-key -n M-1 if-shell\
    'tmux select-window -t :1'\
    ''\
    'new-window -t :1'
bind-key -n M-! if-shell\
    'tmux join-pane -bt :1.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :1'

# window 2
bind-key -n M-2 if-shell\
    'tmux select-window -t :2'\
    ''\
    'new-window -t :2'
bind-key -n M-@ if-shell\
    'tmux join-pane -t :2.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :2'

# window 3
bind-key -n M-3 if-shell\
    'tmux select-window -t :3'\
    ''\
    'new-window -t :3'
bind-key -n M-# if-shell\
    'tmux join-pane -t :3.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :3'

# window 4
bind-key -n M-4 if-shell\
    'tmux select-window -t :4'\
    ''\
    'new-window -t :4'
bind-key -n M-$ if-shell\
    'tmux join-pane -t :4.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :4'

# window 5
bind-key -n M-5 if-shell\
    'tmux select-window -t :5'\
    ''\
    'new-window -t :5'
bind-key -n M-% if-shell\
    'tmux join-pane -t :5.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :5'

# window 6
bind-key -n M-6 if-shell\
    'tmux select-window -t :6'\
    ''\
    'new-window -t :6'
bind-key -n M-^ if-shell\
    'tmux join-pane -t :6.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :6'

# window 7
bind-key -n M-7 if-shell\
    'tmux select-window -t :7'\
    ''\
    'new-window -t :7'
bind-key -n M-& if-shell\
    'tmux join-pane -t :7.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :7'

# window 8
bind-key -n M-8 if-shell\
    'tmux select-window -t :8'\
    ''\
    'new-window -t :8'
bind-key -n M-* if-shell\
    'tmux join-pane -t :8.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :8'

# window 9
bind-key -n M-9 if-shell\
    'tmux select-window -t :9'\
    ''\
    'new-window -t :9'
bind-key -n M-( if-shell\
    'tmux join-pane -t :9.#{top-left} && tmux select-layout main-vertical'\
    ''\
    'break-pane -t :9'


# copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsel -i -p -b'
bind-key -n M-P copy-mode
bind-key -n M-p paste-buffer

# startup script sets pane dimensions based on window size
run-shell -b /home/jfin/scripts/set-pane-size-tmux
