set -g default-command "R --quiet --no-save"
set -g status off
set -g message-style fg=white,bg=default
set -g mode-keys vi
bind-key -n M-: command-prompt
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'cat > /dev/clipboard'
bind-key -n M-[ copy-mode
