#!/bin/sh
# checkout dotfiles into new home dir

if [ -z "$1" ]
then
	echo "Usage: $0 <branch>"
	exit
fi

git config --global user.name "John Inman"
git config --global user.email jfinmaniv@icloud.com
git config --global credential.helper store

git clone --bare https://github.com/jfinmaniv/dotfiles $HOME/.dot.git

function dot {
   git --git-dir=$HOME/.dot.git/ --work-tree=$HOME "$@"
}

dot checkout "$1"

if [ "$?" = 0 ]
then
	echo "Checked out dot files."
else
	mkdir dotfiles.bak
	echo "Backing up pre-existing dot files."
	dot checkout "$1" 2>&1 \
		| egrep "\s+\." \
		| awk {'print $1'} \
		| xargs -I{} mv {} dotfiles.bak/{}
fi

dot checkout "$1"
dot config --local status.showUntrackedFiles no
dot push --set-upstream origin "$1"
