" first thing's first
syntax on
filetype indent on
filetype plugin on
colorscheme jfin

" define variables
let mapleader = ' '
let maplocalleader = ' '

" other options
set autoread 
set autowriteall
set background=dark
set belloff=all
" set completeopt=menuone,longest
set completeopt=menuone
set encoding=utf-8
set fillchars-=vert:\\|
set formatoptions=qlcjnr
set hlsearch
set ignorecase 
set incsearch
set mouse=
set pastetoggle=<insert> 
set scrolloff=5
set shell=bash
" set shortmess-=S
set ruler
set signcolumn=no
set smartcase 
set t_Co=16
set ttimeoutlen=0 " exit command line mode immediately
set undofile 
set virtualedit=block
set wildmenu
set wildmode=full

" dir options
set backupdir=~/.vim/backup
set directory=~/.vim/swap
set undodir=~/.vim/undo 
set viewdir=~/.vim/view
set viminfo+=n~/.vim/.viminfo

" maps
nnoremap <cr> :write<cr>
nnoremap <silent> <esc> :noh<cr>
tnoremap <esc><esc> <c-\><c-n>
tnoremap :: <c-w>:
nnoremap <leader>n /=expand('<cword>')<cr><cr>

" indentation
set autoindent 
set breakindent 
set breakindentopt=shift:0
set expandtab 
set linebreak 
set shiftround 
set shiftwidth=4
set showbreak=+++\ 
set tabstop=4
set textwidth=78 

" folds
set foldlevelstart=0
set foldmethod=marker

" snippets
let g:snipMate = get(g:, 'snipMate', {
            \ 'always_choose_first' : 1,
            \ 'no_match_completion_feedkeys_chars' : '',
            \ })
inoremap <c-l> <Plug>snipMateNextOrTrigger
snoremap <c-l> <Plug>snipMateNextOrTrigger
inoremap <c-h> <Plug>snipMateBack
snoremap <c-h> <Plug>snipMateBack
augroup snipmate
   au!
   autocmd bufleave *.snippets SnipMateLoadScope %
augroup end

" mucomplete
let g:mucomplete#no_mappings = 1
let g:mucomplete#chains = {
    \ 'default' : ['path', 'keyp', 'omni', 'dict', 'uspl'],
    \ }
inoremap <tab> <plug>(MUcompleteFwd)
inoremap <s-tab> <plug>(MUcompleteBwd)
inoremap <c-j> <plug>(MUcompleteCycFwd)
inoremap <expr> l mucomplete#extend_bwd("l")

" get highlight group
function! GetHighlight()
    let hi    = synIDattr(synID(line('.'), col('.'), 1), 'name')
    let trans = synIDattr(synID(line('.'), col('.'), 0), 'name')
    let lo    = synIDattr(synIDtrans(synID(line('.'), col('.'), 1)), 'name')
    echo 'hi:' . hi . ', trans:' . trans . ', lo:' . lo
endfunction

" source updated config files 
augroup vimrc
    au!
    autocmd BufWritePost vimrc source <afile>
    autocmd BufWritePost */plugin/*.vim  source <afile>
    autocmd BufWritePost */colors/*.vim  source <afile>
augroup end

" fzf
let g:fzf_colors = { 'border':  ['fg', 'vertsplit'] }

"lsp
let g:lsp_use_native_client = 1
let g:lsp_semantic_enabled = 0
let g:lsp_format_sync_timeout = 1000
let g:lsp_diagnostics_enabled = 0
let g:lsp_settings_enable_suggestions = 0
let g:lsp_completion_documentation_enabled = 0
let g:lsp_signature_help_enabled = 0
inoremap <c-k> <c-o><plug>(lsp-signature-help)
set omnifunc=lsp#complete

" sideways
nnoremap <leader>ah :SidewaysLeft<cr>
nnoremap <leader>al :SidewaysRight<cr>

" utilities

function! Win2Unix()
    execute 's/\\/\//g'
    execute 's/[cC]:\//\/c\/'
endfunction
command! Win2Unix silent! call Win2Unix()

function! Start()
    let link = getline(line('.'))->substitute('^"\|"$', '', 'g')
    execute printf('call system(''launch-file "%s"'')',
                \ link)
endfunction
command! Start call Start()

" markdown
let g:vim_markdown_conceal = 2
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_new_list_item_indent = 0
set conceallevel=2

command! Todo BLines #todo

" copy to clipboard
function! CopyToClipboard(type = '') abort
    
    " operator boilerplate >>>
    if a:type == ''
        let &operatorfunc = 'CopyToClipboard'
        return 'g@'
    endif
    let selection = {
                \ 'line': "'[V']",
                \ 'char': "`[v`]",
                \ 'block': "`[\<C-V>`]",
                \ }[a:type]
    " <<<
    
    " os specific
    if has("win64")
        execute printf('normal! %s"*y',
                    \ selection)
    elseif has("unix")
        execute printf('normal! %s"+y',
                    \ selection)
    endif
endfunction
nnoremap <expr> Y CopyToClipboard()
xnoremap <expr> Y CopyToClipboard()
nnoremap <expr> YY CopyToClipboard() .. '_'

" Create or clear an augroup
augroup mutt
    autocmd!
    autocmd insertenter,bufwrite /tmp/neomutt* ++once setfiletype mail
augroup END

