#!/usr/bin/env zsh

docker run --rm -it \
  -e OPENROUTER_API_KEY=$(< ~/.secrets/openrouter-api-key) \
  -e BRAVE_API_KEY=$(< ~/.secrets/brave-api-key) \
  -v "$PWD:/workspace" \
  -v pi-agent-home:/root/.pi/agent \
  pi-sandbox
