#!/bin/sh
# add, commit, and push etc changes

if [ -z "$*" ]
then 
	doas git --git-dir=/etc/.etc.git/ --work-tree=/etc status
	echo -e "\nRun \"${0##*/} <commit message>\" to commit changes"
	exit
fi

doas git --git-dir=/etc/.etc.git/ --work-tree=/etc add .
doas git --git-dir=/etc/.etc.git/ --work-tree=/etc commit -m "$*"
doas git --git-dir=/etc/.etc.git/ --work-tree=/etc push
