#!/bin/sh
# add, commit, and push dotfile changes

if [ -z "$*" ]
then 
	git --git-dir=$HOME/.dot.git/ --work-tree=$HOME status
	echo -e "\nRun \"${0##*/} <commit message>\" to commit changes"
	exit
fi

git --git-dir=$HOME/.dot.git/ --work-tree=$HOME add .
git --git-dir=$HOME/.dot.git/ --work-tree=$HOME commit -m "$*"
git --git-dir=$HOME/.dot.git/ --work-tree=$HOME push
