#!/bin/sh

git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add -u
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add .bin
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME commit -m "${*:-no message}"
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME push

