#!/usr/bin/env zsh

wg-quick up ~/.wg/us-sjc-wg-302.conf &> /dev/null &

until sudo wg show interfaces | grep -q "."; do
    echo "connecting to vpn..."
    sleep 1
done

xsetroot -name "$(get-status)"

qbittorrent-nox &> /dev/null &
PID=$!

until curl -s localhost:8080 | grep -q "qBittorrent"; do
    echo "starting qbittorrent..."
    sleep 1
done

firefox localhost:8080 &> /dev/null &

echo "ready..."

trap '
    kill $PID
    wg-quick down ~/.wg/us-sjc-wg-302.conf &> /dev/null
    xsetroot -name "$(get-status)"
    trap - INT
' INT

wait $PID
