#!/usr/bin/env zsh

case $1 in
  pods) device=18:3F:70:5E:41:D0 ;;
  xm3s) device=70:26:05:CF:75:A1 ;;
  *) huh? ;;
esac

bluetoothctl info | grep 'Connected: yes' \
  && action=disconnect \
  || action=connect

bluetoothctl $action $device

xsetroot -name "$(get-status)"
