#!/usr/bin/env zsh

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <remote> <dir1> [dir2 ...]" >&2
  exit 1
fi

remote="${@[1]}"   # last argument
dirs=("${@[2,-1]}") # everything except the last argument

if [[ "$remote" != "docs" && "$remote" != "data" ]]; then
    echo "Error: remote must be 'docs' or 'data' (got '$remote')" >&2
    exit 1
fi

for dir in "${dirs[@]}"; do
    rclone --progress copy "$remote:$dir" "$dir"
done
