#!/bin/sh

dir=$HOME/waterboard/notes/
new=false
copy=false
OPTIND=1
while getopts 'nc' arg
do
    case "${arg}" in
        n) new=true ;;
        c) copy=true ;;
        *) return ;;
    esac
done
shift $((OPTIND-1))

if $new
then
    dayno=$(date +'%y%j')

    i=a
    while [ -e $dir/${dayno}${i}.txt ]
    do
        if [ $i = "z" ]
        then
            echo "too many notes today"
            return 1
        else
            i=$(echo $i | tr "a-y" "b-z")
        fi
    done

    print -s vim $dir/${dayno}${i}.txt
    vim $dir${dayno}${i}.txt

    return
fi

cd $dir
match=$(grep -ir "${1:-.}"\
    | sed -e 's/: */:/'\
    | sort -k2\
    | fzy)
file=${match%%:*}
line=${match#*:}
cd "$OLDPWD"

if [ -z "$file" ]
then
    return
fi

if $copy
then
    print -n $dir$file > /dev/clipboard
    return
fi

print -s vim $dir$file
vim -c "call search(\"$line\")" $dir$file
