#!/bin/sh

cd $HOME/.pass
account=$(\
    fd --path-separator // ${*:-.} |\
    sed -e 's/.*\/\(.*\/.*\)\.gpg/\1/' |\
    fzf --height 40% --reverse\
)
password=$(cat $account)
if [[ $password ]]; then
    old_clipboard=$(< /dev/clipboard)
    echo -n "$password" > /dev/clipboard
    (
    { sleep 10
        echo -n "$old_clipboard" > /dev/clipboard
    } & 
)
fi
cd - > /dev/null
