#!/bin/sh
pw () {
command="fzf --height 40% --reverse"
[[ -n "$*" ]] && command="fzf --query $* --height 40% --reverse"
account=$(\
    fd --path-separator // gpg $HOME/.password-store |\
    sed -e 's/.*\/\(.*\/.*\)\.gpg/\1/' |\
    $command
)
    password=$(pass show $account)
    if [[ $password ]]; then
        old_clipboard=$(< /dev/clipboard)
        echo -n "$password" > /dev/clipboard
        (
        { sleep 10
            echo -n "$old_clipboard" > /dev/clipboard
        } & 
    )
    fi
}

