#!/bin/sh

pw_dir=~/.secrets
file=$(ls $pw_dir | fzf -q ${1:-""})
pw=$(head $pw_dir/$file -n1)
if [[ $pw ]]; then
    clipboard=$(< /dev/clipboard)
    echo -n "$pw" > /dev/clipboard
    (
        { sleep 10
            echo -n "$clipboard" > /dev/clipboard
        } &
    )
fi
