#!/usr/bin/zsh

start_linux() {
    file="$1"
    if [[ "$ext" == eml ]]; then
        xterm -e view-mail "$file"
    else
        xdg-open "$file"
    fi
}

start_msys() {
    # file="${1/\/c/c:}"
    file="$1"
    if [[ "$ext" == pdf ]]; then
        SumatraPDF-3.5.2-64 "$file" > /dev/null 2>&1
    else
        cmd //c start "" "$file"
    fi
}

os=$(uname)
for f in $@; do
    ext="${1##*.}"
    if [[ $os == "Linux" ]]; then
        start_linux "$f" &> /dev/null &
    else
        start_msys "$f" &> /dev/null &
    fi
done

