#!/bin/sh

echo rclone sync --progress data:resources ~/resources
rclone sync --progress data:resources ~/resources
echo
echo rclone sync --progress docs:notes ~/notes
rclone sync --progress docs:notes ~/notes
echo
echo rclone sync --progress docs:projects ~/projects
rclone sync --progress docs:projects ~/projects
echo
echo rclone sync --progress docs:relep ~/relep --exclude="/ReLEP/**" --exclude="/Region **"
rclone sync --progress docs:relep ~/relep --exclude="/ReLEP/**" --exclude="/Region **"
echo
echo git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME pull
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME pull
