#!/usr/bin/env bash

# copy files from staging area to transfer between personal and work computers
# delete extraneous files

dirs="notes projects records resources"

for dir in $dirs; do 
  rsync -ahP --delete jfin-wb@10.0.0.10:staged/$dir ~/$dir
done
