#!/usr/bin/env zsh

run_copy() {
    local store=$1; shift
    for dir in "$@"; do
        echo
        echo "$dir ------------------------------------------------------------------------------"
        rclone --progress copy $store:$dir ~/$dir
    done
}

tmux split-window -h "zsh -c '$(typeset -f run_copy); run_copy docs notes projects records; exec zsh'"
tmux split-window -h "zsh -c '$(typeset -f run_copy); run_copy data resources; exec zsh'"

tmux select-layout main-vertical
