#!/usr/bin/env zsh

# pull from cloud
pfc() {
    local remote=$1
    local dir=$2
    tmux split-window -h "
        printf '%s\n' $remote:$dir
        for i in {1..78}; do printf '-'; done
        printf '\n'
        rclone --progress copy $remote:$dir ~/$dir
        exec zsh
    "
    tmux select-layout main-vertical
}

pfc docs notes
pfc docs projects
pfc docs records
pfc data resources
