#!/bin/sh

echo rclone sync --progress ~/notes docs:notes 
rclone sync --progress ~/notes docs:notes 
echo
echo rclone sync --progress ~/projects docs:projects 
rclone sync --progress ~/projects docs:projects 
echo 
echo rclone sync --progress ~/relep docs:relep --exclude="/ReLEP/**"
rclone sync --progress ~/relep docs:relep --exclude="/ReLEP/**"
echo 
echo rclone sync --progress ~/resources data:resources 
rclone sync --progress ~/resources data:resources 
echo

add-commit-push-dotfiles
