#!/bin/sh

print_header() {
    text="$1 "
    pad_length=$((78 - ${#text}))
    printf "\n%s " $text
    printf "%0.s-" $(seq 1 $pad_length)
    printf "\n"
}

print_header "docs:notes"
rclone sync --update --progress ~/notes docs:notes 
print_header "docs:projects"
rclone sync --update --progress ~/projects docs:projects 
print_header "docs:records"
rclone sync --update --progress ~/records docs:records 
print_header "docs:relep"
rclone sync --update --progress ~/relep docs:relep --exclude="/ReLEP/**" --exclude="/Region **"
print_header "data:resources"
rclone sync --update --progress ~/resources data:resources 
print_header "dotfiles"
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME add -u
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME commit -m "automatic commit"
git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME push
