#!/usr/bin/env bash

# copy files to staging area to transfer between personal and work computers

dirs="notes projects records resources"

for dir in $dirs; do 
  rsync -ahP ~/$dir jfin-wb@10.0.0.10:staged
done
