#!/usr/bin/env zsh

# push to cloud
ptc() {
    local remote=$1
    local dir=$2
    tmux split-window -h "
        printf '%s\n' $remote:$dir
        for i in {1..78}; do printf '-'; done
        printf '\n'
        rclone --progress --exclude "archive/**" sync ~/$dir $remote:$dir 
        exec zsh
    "
    tmux select-layout main-vertical
}

ptc docs notes
ptc docs projects
ptc docs records
ptc data resources
