#!/bin/sh
# rank mirrors

sudo sh -c "\
	curl -s 'https://www.archlinux.org/mirrorlist/?country=US&country=GB&protocol=https&use_mirror_status=on'\
	| sed -e 's/^#Server/Server/' -e '/^#/d'\
	| rankmirrors -n 5 - > /etc/pacman.d/mirrorlist"
