#!/bin/sh
# record video

if [ $1 ]; then
	filename="${1}"
else
	filename="webcam-$(date '+%Y%m%d%H%M%S').mp4"
fi

ffmpeg\
	-f v4l2\
	-video_size 640x480\
	-i /dev/video0\
	-f alsa\
    -i default\
	-c:v libx264\
	-preset ultrafast\
	-c:a aac\
	$filename
