#!/bin/sh

# Edit file names in a text editor

# we need two arrays: one for the original names and one for the new names.
# posix only has one array (for positional parameters). we'll use it for the
# original file names and handle the new file names in a loop.
set -- *

# Setting IFS to <newline>. This will put each file name on it's own line.
IFS='
'
temp=$(mktemp)
# put each arg of "$*" on a new line
echo "$*" > $temp

# edit names
$EDITOR $temp

# Set IFS to <nul> to prevent word splitting
IFS=

# -r: treat "\" literally rather than escape character
while read -r f; do
    if [ "$f" != "$1" ]
    then
        # -n: no clobber; -v: verbose output
        # use first element
        mv -nv "$1" "$f"
    fi
    # discard first element
    shift
done < $temp
