#!/usr/bin/env bash

# # notes
# notes() {
#     notes_file="$HOME/notes/notes.txt"
#     line=$(\
#         rg --line-number "${*:-.}" "$notes_file" |\
#         fzf --height 40% --reverse |\
#         sed -e 's/:.*//'
#         )
#     if [[ $line ]]; then
#         vim +$line "$notes_file"
#     fi
# }

# : | rg_prefix='rg --column --line-number --no-heading --color=always --smart-case' \
#     fzf --bind 'start:reload:$rg_prefix ""' \
#         --bind 'change:reload:$rg_prefix {q} || true' \
#         --bind 'enter:become(vim {1} +{2})' \
#         --ansi --disabled \
#         --height=50% --layout=reverse


# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in Vim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q} " \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --delimiter : \
    --bind 'enter:become(vim {1} +{2})'
    # --preview 'cat' \
    # --bind 'enter:become(vim)'
    # --preview 'bat --color=always {1} --highlight-line {2}' \
    # --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
