#! /bin/ksh
# change wireless access point

case $1 in
	coffeebean) wap='nwid CBTL_Guest wpakey coffee12' ;; # on 5 cities dr
	coastalpeaks) wap='nwid CoastalPeaksCoffee wpakey coastalpeaks' ;;
	eastbathhouse) wap='nwid "East Bath House"' ;; 
	nonna) wap='nwid ORBI07 wpakey luckgadfly646' ;;
	officedepot) wap='nwid OfficeDepot' ;;
	suetorrey) wap='nwid NETGEAR53 wpakey aquaticsun358' ;;
	waterboard) wap='nwid SWRCB_Public3 wpakey 8055493147' ;;
    agrarian) wap='nwid "Agrarian Guest" wpakey Agrarian' ;;
    andreini) wap='nwid "Cafe Andreini WiFi" wpakey happythoughts' ;;
    dad) wap='nwid MOTOROLA-5FE55 wpakey 78897a00951425b87d73' ;;
    netgear) wap='nwid NETGEAR85 wpakey jollyearth812' ;;
    netgear5G) wap='nwid NETGEAR85-5G wpakey jollyearth812' ;;
    aglibrary) wap='nwid Arroyo_Grande_Library' ;;
	linnaeas) wap="nwid \"Linnaea's WiFi Guest-2G\" wpakey lemondrop" ;;
    mom) wap='nwid ATT8JGd4jl_2GEXT wpakey 99gud35nnk88' ;;
    jfinmaniv) wap='nwid jfinmaniv wpakey 011235813' ;;
    sandbox) wap='nwid "THE SANDBOX WiFi"' ;; # in santa barbara
    starbucks) wap='nwid "Google Starbucks"' ;;
    tribe) wap='nwid "Tribe Coffeehouse guest" wpakey mytribe1' ;;
esac

# print "$wap \ndhcp lladdr random" > /tmp/hostname.iwm0
print "$wap \ndhcp" > /tmp/hostname.iwm0
doas cp /tmp/hostname.iwm0 /etc
doas /etc/netstart
wait 
status &
ping -c 3 google.com
