#!/bin/bash

# Get current time in seconds
now=$(date +%s)

# Calculate seconds for 2 AM on next Mon/Wed/Sat
mon=$(date -d "next monday 02:00" +%s)
wed=$(date -d "next wednesday 02:00" +%s)
sat=$(date -d "next saturday 02:00" +%s)

# Find the smallest (earliest) time
earliest=$mon
[ $wed -lt $earliest ] && earliest=$wed
[ $sat -lt $earliest ] && earliest=$sat

# Set RTC wake and suspend
nohup sudo bash -c "sleep 3; rtcwake -m mem -t $earliest" &> /dev/null &
pkill sshd-session
