#!/usr/bin/zsh

start_torrents() {
    sudo mount /dev/disk/by-label/storage /mnt/storage
    wg-quick up ~/.wg/us-sjc-wg-302.conf
    sleep 1
    if curl -s https://am.i.mullvad.net/connected | grep -q "not connected"; then
        echo "couldn't connect to mullvad"
        exit
    fi
    xsetroot -name "$(get-status)"
    qbittorrent-nox &
    PID=$!
    sleep 1
    firefox localhost:8080 &
    trap '
        kill $PID
        wg-quick down ~/.wg/us-sjc-wg-302.conf
        xsetroot -name "$(get-status)"
        trap - INT
    ' INT
    wait $PID
}

echo running qbittorrent...
start_torrents &> /dev/null
