#!/usr/bin/env zsh

sudo mount /dev/disk/by-label/storage /mnt/storage

wg-quick up ~/.wg/us-sjc-wg-302.conf 

until curl -s https://am.i.mullvad.net/connected | grep -q "are connected"; do
    echo "connecting to vpn..."
    sleep 1
done

xsetroot -name "$(get-status)"

qbittorrent-nox &> /dev/null &
PID=$!

until curl -s localhost:8080 | grep -q "qBittorrent"; do
    echo "starting qbittorrent"
    sleep 1
done

firefox localhost:8080 &> /dev/null &

trap '
    kill $PID
    wg-quick down ~/.wg/us-sjc-wg-302.conf &> /dev/null
    xsetroot -name "$(get-status)"
    trap - INT
' INT

wait $PID
