#!/usr/bin/env bash

sep="    "

VPN() {
    if sudo wg show interfaces | grep -q "."; then
        echo VPN"$sep"
    fi
}

Bluethooth() {
    devices="XM3"
    for dev in ${devices}; do
        if bluetoothctl devices Connected | grep -qi $dev; then
            echo $dev"$sep"
        fi
    done
}

Layout() {
    echo "$(</run/keyd-layout)$sep"
}

Date() {
    echo $(date +'%a %b %d')"$sep"
}

Time() {
    echo $(date +'%H %M')
}

status=$(Bluethooth)$(VPN)$(Layout)$(Date)$(Time)
echo "${status}"
