#!/usr/bin/env bash

# copy files from staging area to transfer between personal and work computers
# delete extraneous files

dirs="notes projects records resources"
remote=jfin@10.0.0.40:/var/www/htdocs/wb

for dir in $dirs; do

  case $1 in
    push) cmd="rsync -ahP ~/$dir $remote" ;;
    pull) cmd="rsync -ahP --delete $remote/$dir ~/" ;;
    *) echo "usage: $0 push|pull" >&2; exit 1 ;;
  esac

  tmux split-window -dh "$cmd || read"
  tmux select-layout main-vertical

done
