#!/usr/bin/env bash

# copy files from staging area to transfer between personal and work computers
# delete extraneous files

dirs="notes projects records resources"
root=/var/www/htdocs/wb

for dir in $dirs; do

  hostname=$(uname -n)

  case $hostname in
    WB-102492) 
      case $1 in
        # server defined in rclone config
        push) cmd="rclone -P copy ~/$dir server:$root/$dir" ;;
        pull) cmd="rclone -P -f'- old/**' sync server:$root/$dir ~/$dir" ;;
        *) echo "usage: $0 push|pull" >&2; exit 1 ;;
      esac
      ;;
    desktop) 
      case $1 in
        # server defined in ssh config
        push) cmd="rsync -ahP ~/$dir server:$root" ;;
        pull) cmd="rsync -ahP -f'- old/' --delete server:$root/$dir ~/" ;;
        *) echo "usage: $0 push|pull" >&2; exit 1 ;;
      esac
      ;;
    *) echo "unknown host: $hostname" ;;
  esac

  [[ -z "$TMUX" ]] && echo run in tmux && exit
  tmux split-window -dh "echo $dir; $cmd || read"
  tmux select-layout main-vertical

done
