#!/usr/bin/env bash

# copy files from staging area to transfer between personal and work computers
# delete extraneous files

dirs="notes projects records resources"
host=jfin@10.0.0.40
root=/var/www/htdocs/wb

for dir in $dirs; do

  hostname=$(uname -n)

  case $hostname in
    WB-102492) 
      case $1 in
        push) cmd="rclone -P copy ~/$dir server:$root" ;;
        pull) cmd="rclone -P -f'- old/**' sync server:$root/$dir ~/" ;;
        *) echo "usage: $0 push|pull" >&2; exit 1 ;;
      esac
      ;;
    jfin) 
      case $1 in
        push) cmd="rsync -ahP ~/$dir $host:$root" ;;
        pull) cmd="rsync -ahP -f'- old/' --delete $host:$root/$dir ~/" ;;
        *) echo "usage: $0 push|pull" >&2; exit 1 ;;
      esac
      ;;
    *) echo "unknown host: $hostname" ;;
  esac

  tmux split-window -dh "echo $dir; $cmd || read"
  tmux select-layout main-vertical

done
