#!/usr/bin/env zsh

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <dir1> [dir2 ...] <remote>" >&2
  exit 1
fi

remote="${@[-1]}"   # last argument
dirs=("${@[1,-2]}") # everything except the last argument

if [[ "$remote" != "docs" && "$remote" != "data" ]]; then
  echo "Error: remote must be 'docs' or 'data' (got '$remote')" >&2
  exit 1
fi

for dir in "${dirs[@]}"; do
    rclone \
        --progress \
        --filter '+ .RData' \
        --filter '- .*' \
        --filter '- .*/**' \
        --filter '- old/**' \
        --filter '- resources/**' \
        --filter '- refs/**' \
        sync "$dir" "$remote:$dir"
done
