#!/bin/sh

# process options
OPTIND=1
unset new copy todo
while getopts 'nc' arg; do
    case "${arg}" in
        n) new=yes ;;
        c) copy=yes ;;
        *) echo unknown option; exit ;;
    esac
done
shift $((OPTIND-1))

# if new note, edit new file and quit when finished
if [ "$new" = yes ]; then
    dayno=$(date +'%y%j')
    i=a
    while [ -e $HOME/notes/${dayno}${i}.txt ]
    do
        if [ $i = "z" ]; then
            echo "too many notes today"
            exit 1
        else
            i=$(echo $i | tr "a-y" "b-z")
        fi
    done
    vim $HOME/notes/${dayno}${i}.txt
    print -s vim $HOME/notes/${dayno}${i}.txt
    exit
fi

# select file
cd $HOME/notes
clear
match=$(grep -ir --exclude-dir=".git" --exclude="README.md" "${*:-.}"\
    | sed -e 's/: \+/:/'\
    | sort --reverse\
    | fzy -l$(( LINES - 1 )))
file=${match%%:*}
line=${match##*:}
cd "$OLDPWD"

# if none selected, then do nothing and quit
if [ -z "$file" ]; then
    exit
fi

# if all we want is the path, then send it to the clipboard and quit
if [ "$copy" = yes ]; then
    echo -n $HOME/notes/$file > /dev/clipboard
    echo path copied to clipboard
    exit
fi

# edit the selected file
vim -c "call search(\"$line\$\")" $HOME/notes/$file
print -s vim $HOME/notes/$file
