#! /bin/ksh
# restart openvpn

if [[ -z $1 ]]
then
	config=$HOME/.ovpn/us-free-01.protonvpn.com.udp.ovpn
else
	config=$1
fi

ovpn_pid=$(pgrep openvpn)

case $1 in
    off ) 
        if [[ -n $ovpn_pid ]] 
        then
            doas kill -KILL $ovpn_pid
            doas rm /etc/dhclient.conf 
        fi
        doas /etc/netstart
        wait
        ping -c 3 google-public-dns-a.google.com 
        ;;
    halt ) 
        if [[ -n $ovpn_pid ]] 
        then
            doas kill -KILL $ovpn_pid
            doas rm /etc/dhclient.conf 
        fi 
        ;;
    * ) 
        if [[ -n $ovpn_pid ]] 
        then
            doas kill -KILL $ovpn_pid
            doas rm /etc/dhclient.conf 
        fi
        doas cp $HOME/.ovpn/dhclient.conf /etc
        doas /etc/netstart
        wait
        doas /usr/local/sbin/openvpn --config $config > $HOME/.ovpn/log &
        sleep 10
        if [[ -n $(pgrep openvpn) ]] 
        then
            ping -c 3 google-public-dns-a.google.com 
        else
            cat $HOME/.ovpn/log
        fi 
        ;;
esac 
