#!/bin/bash

dir=$HOME/.aur

for p in $dir/*; do

    if [[ "$p" == "$dir/${0##*/}" ]]; then
        # do not try to update this script
        continue
    fi
     
    text=${p##*/}
    pad=$((78 - ${#text}))
    printf "\n%s" $text
    printf "%0.s-" $(seq 1 $pad)
    printf "\n"

    if [[ "$p" == "$dir/dwm" ]]; then
        git --git-dir="${p}/.git" --work-tree="$p" switch master 
        if git --git-dir="${p}/.git" --work-tree="$p" pull | grep -q "Already up to date\\."; then
            is_already_up_to_date=true
        else
            is_already_up_to_date=false
        fi
        git --git-dir="${p}/.git" --work-tree="$p" switch patched
        git --git-dir="${p}/.git" --work-tree="$p" rebase --rebase-merges master
    else
        if git --git-dir="${p}/.git" --work-tree="$p" pull | grep -q "Already up to date\\."; then
            is_already_up_to_date=true
        else
            is_already_up_to_date=false
        fi
    fi >& /dev/null

    if $is_already_up_to_date; then
        echo already up to date
    else
        makepkg \
            --clean \
            --syncdeps \
            --install \
            --noconfirm \
            --dir "$p"
    fi
    
done
