#!/usr/bin/env zsh

[[ -f ~/.keyd_layout ]] || echo xwin > ~/.keyd_layout

layout=$(<~/.keyd_layout)

[[ $layout == xwin ]] && layout=tmux || layout=xwin

echo $layout > ~/.keyd_layout

xsetroot -name "$(get-status)"
