#!/usr/bin/env zsh

[[ -e /tmp/keyd-status ]] || echo xwin > /tmp/keyd-status
keyd listen | while read -r line; do
    if [[ $line == /* ]]; then
        if [[ $line == /xwin ]]; then
            echo xwin > /tmp/keyd-status
        else
            echo tmux > /tmp/keyd-status
        fi
        xsetroot -name "$(get-status)"
    fi
done
