#!/bin/bash

dir=$HOME/.aur

for p in $dir/*; do

    if [[ "$p" == "$dir/${0##*/}" ]]; then
        # do not try to update this script
        continue
    fi
     
    text="$p "
    pad_length=$((78 - ${#text}))
    printf "\n%s " $text
    printf "%0.s-" $(seq 1 $pad_length)
    printf "\n"

    if [[ "$p" == "$dir/dwm" ]]; then
        git --git-dir="${p}/.git" --work-tree="$p" switch master 
        git --git-dir="${p}/.git" --work-tree="$p" pull
        git --git-dir="${p}/.git" --work-tree="$p" switch patched
        git --git-dir="${p}/.git" --work-tree="$p" rebase --rebase-merges master
    else
        git --git-dir="${p}/.git" --work-tree="$p" pull
    fi

    makepkg \
        --clean \
        --syncdeps \
        --install \
        --noconfirm \
        --dir "$p"
    
done
