#!/usr/bin/env zsh

file=/run/keyd-status
sudo touch $file
sudo chmod 777 $file
echo xwin > $file
while read -r line; do
    if [[ $line == /* ]]; then
        [[ $line == /xwin ]] && echo xwin > $file
        [[ $line == /tmux ]] && echo tmux > $file
        xsetroot -name "$(get-status)"
    fi
done < <(keyd listen)
