#!/bin/sh

# addition vars due to invoking from cron
# more here:
# https://wiki.archlinux.org/title/Desktop_notifications#Usage_in_programing

capacity=$(< /sys/class/power_supply/BAT0/capacity)
status=$(< /sys/class/power_supply/BAT0/status)
if [[ $status = Discharging ]] && [[ $capacity -le 10 ]]; then
    sudo -u $USER \
        DISPLAY=:0 \
        DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus \
        notify-send --expire-time=10000 --urgency=critical "Battery ${capacity}%"
fi
