#!/bin/sh

brightness=$(< /sys/class/backlight/intel_backlight/brightness)
brightness=$(printf "%.0f" "$(echo "$brightness * 0.8" | bc -l)")

if [[ $brightness -eq 0 ]]; then
    brightness=1
fi

sudo sh -c "echo $brightness > /sys/class/backlight/intel_backlight/brightness"
