#!/bin/sh

# get --bootnum to modify instead of --create
# efibootmgr

# get efi disk and partition
# lsblk

# resume must be uuid because swapfile is on filesytem

# get resume_offset
# filefrag -v /swapfile | awk '{if($1=="0:"){print $4}}' | sed 's/\.\.//'

# NOTE: /etc/mkinitcpio.conf must have 'resume' in HOOKS(...)

sudo efibootmgr \
  --create \
  --disk /dev/nvme0n1 \
  --part 1 \
  --label "Arch Linux" \
  --loader /vmlinuz-linux \
  --unicode 'root=PARTUUID=c0010138-6f1d-4631-82c3-87dfe63c3ff2 rw initrd=\initramfs-linux.img resume=UUID=c26bc8d7-8ea5-44f1-8b21-9ec5dab753af resume_offset=5059034' \
  --verbose

